homepage/urls.py
from django.urls import path
from .views import index, delete_status

app_name = 'homepage'

urlpatterns = [
    path('', index, name='index'),
    path('<int:query_id>', delete_status, name='delete'),
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('homepage.urls'))
]

homepage/models.py
from django.db import models
import datetime


# Create your models here.

class Status(models.Model):
    status = models.CharField(max_length = 300, default='status')
    time = models.DateTimeField(auto_now_add=True, editable=False, null=False, blank=False)

    def __str__(self):
        return self.status

homepage/forms.py
from django import forms

class StatusForm(forms.Form):
    status = forms.CharField(max_length=300, label= '', required=True)
    status.widget.attrs['class'] = 'form-control'
    status.widget.attrs['placeholder'] = 'Your Status'

homepage/views.py
from django.shortcuts import render, redirect
from .models import Status
from .forms import StatusForm


# Create your views here.
def index(request):
    if request.method == 'POST':
        form = request.POST
        clear_form = StatusForm()

        status = Status.objects.create(status = form['status'])
        result = Status.objects.all().order_by('-id')

        response = {
            'result' : result,
            'form' : clear_form,
        }
        return render(request, 'index.html', response)

    else:
        form = StatusForm()
        result = Status.objects.all().order_by('-id')

        response = {
            'form' : form,
            'result' : result,
        }
        return render(request, 'index.html', response)

def delete_status(request, query_id):
    Status.objects.filter(id=query_id).delete()
    return redirect('homepage:index')

homepage/templates/index.html
{% extends 'story6/base.html' %}
{% load static %}

{% block body %}
    <h1 class="text-center mt-5 container">HALO, APA KABAR?</h1>
    <div class="d-flex justify-content-center mt-3">
        <form action="{% url 'homepage:index' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="text-center mt-4">
                <button type="submit" class="btn btn-info btn-outline-light btn-lg" id="submit">SUBMIT</button>
            </div>
        </form>
    </div>
    <div class="container mt-4 mb-4">
        <hr>
    </div>
    <div class="container">
        {% for item in result %}
        <div class="card p-4 m-3 d-flex">
            <div>
                <p>{{ item.status }}</p>
                <p>Posted at {{ item.time }}</p>
            </div>
            <div>
                <form method="POST" action="{% url 'homepage:delete' item.id%}"> {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-lg float-right"  id="post-{{ item.id }}">Delete</button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock body %}

templates/components/head.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>HELLO</title>
<link href="https://fonts.googleapis.com/css?family=Manjari|Montserrat:300,400,500,600|Poppins:400,600|Roboto:100,300,400,500,700,900|Monoton&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/style.css' %}">

templates/story6/base.html
<!DOCTYPE html>
{% load static %}
<head>
  {% block head %}
  {% include 'components/head.html' %}
  {% endblock head %}
</head>
<body>

    {% block body %} 
    
    <!-- extend nanti masuk sini -->
    {% endblock body %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>